import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design System Colors - Using CSS variables
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
          DEFAULT: "var(--color-primary-500)",
        },
        secondary: {
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          950: "var(--color-secondary-950)",
          DEFAULT: "var(--color-secondary-500)",
        },
        background: {
          DEFAULT: "var(--color-background-default)",
          surface: "var(--color-background-surface)",
          elevated: "var(--color-background-elevated)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          disabled: "var(--color-text-disabled)",
          inverse: "var(--color-text-inverse)",
        },
        border: {
          DEFAULT: "var(--color-border-default)",
          subtle: "var(--color-border-subtle)",
          strong: "var(--color-border-strong)",
        },
        error: {
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
          950: "var(--color-error-950)",
          DEFAULT: "var(--color-error-500)",
        },
        warning: {
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          950: "var(--color-warning-950)",
          DEFAULT: "var(--color-warning-500)",
        },
        success: {
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          950: "var(--color-success-950)",
          DEFAULT: "var(--color-success-500)",
        },
        info: {
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          300: "var(--color-info-300)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
          800: "var(--color-info-800)",
          900: "var(--color-info-900)",
          950: "var(--color-info-950)",
          DEFAULT: "var(--color-info-500)",
        },
      },
      fontFamily: {
        display: ["var(--font-inter-tight)", "system-ui", "sans-serif"],
        headline: ["var(--font-inter-tight)", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Monaco", "Consolas", "monospace"],
      },
      fontSize: {
        display: ["var(--font-size-display)", { lineHeight: "var(--line-height-display)", letterSpacing: "var(--letter-spacing-display)" }],
        h1: ["var(--font-size-h1)", { lineHeight: "var(--line-height-h1)", letterSpacing: "var(--letter-spacing-h1)" }],
        h2: ["var(--font-size-h2)", { lineHeight: "var(--line-height-h2)", letterSpacing: "var(--letter-spacing-h2)" }],
        h3: ["var(--font-size-h3)", { lineHeight: "var(--line-height-h3)", letterSpacing: "var(--letter-spacing-h3)" }],
        h4: ["var(--font-size-h4)", { lineHeight: "var(--line-height-h4)", letterSpacing: "var(--letter-spacing-h4)" }],
        h5: ["var(--font-size-h5)", { lineHeight: "var(--line-height-h5)", letterSpacing: "var(--letter-spacing-h5)" }],
        h6: ["var(--font-size-h6)", { lineHeight: "var(--line-height-h6)", letterSpacing: "var(--letter-spacing-h6)" }],
        "body-lg": ["var(--font-size-body-lg)", { lineHeight: "var(--line-height-body-lg)", letterSpacing: "var(--letter-spacing-body-lg)" }],
        body: ["var(--font-size-body)", { lineHeight: "var(--line-height-body)", letterSpacing: "var(--letter-spacing-body)" }],
        "body-sm": ["var(--font-size-body-sm)", { lineHeight: "var(--line-height-body-sm)", letterSpacing: "var(--letter-spacing-body-sm)" }],
        label: ["var(--font-size-label)", { lineHeight: "var(--line-height-label)", letterSpacing: "var(--letter-spacing-label)" }],
        caption: ["var(--font-size-caption)", { lineHeight: "var(--line-height-caption)", letterSpacing: "var(--letter-spacing-caption)" }],
        overline: ["var(--font-size-overline)", { lineHeight: "var(--line-height-overline)", letterSpacing: "var(--letter-spacing-overline)" }],
      },
      fontWeight: {
        thin: "var(--font-weight-thin)",
        light: "var(--font-weight-light)",
        regular: "var(--font-weight-regular)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
        extrabold: "var(--font-weight-extrabold)",
        black: "var(--font-weight-black)",
      },
      spacing: {
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        "2xl": "var(--spacing-2xl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        // Legacy sidebar/tile spacing (to be migrated)
        "sidebar-expanded": "280px",
        "sidebar-collapsed": "64px",
        "sidebar-offset": "var(--spacing-sm)",
        "tile-gap": "var(--spacing-md)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
        // Legacy values
        tile: "var(--radius-md)",
        card: "var(--radius-lg)",
      },
      boxShadow: {
        none: "var(--shadow-none)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        inner: "var(--shadow-inner)",
        // Legacy values
        tile: "var(--shadow-md)",
        "tile-hover": "var(--shadow-lg)",
        sidebar: "var(--shadow-xl)",
        "sidebar-hover": "var(--shadow-2xl)",
      },
      transitionDuration: {
        fast: "150ms",
        base: "200ms",
        slow: "300ms",
        slower: "500ms",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-in-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in-left": "slide-in-left 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      aspectRatio: {
        tile: "4 / 3",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require("tailwindcss-animate")
  ],
};

export default config;